# Generated by Django 6.0.4 on 2026-05-01 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_claim_stg_corrections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='fever_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of fever in days (for Enteric Fever)', null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='has_cbc_report',
            field=models.BooleanField(default=False, help_text='Required for Enteric Fever'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='has_diagnostic_report',
            field=models.BooleanField(default=False, help_text='USG / CBC+ESR+LFT / X-ray / Hb report'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='has_histopathology_report',
            field=models.BooleanField(default=False, help_text='Required for Cholecystectomy'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='has_implant_invoice',
            field=models.BooleanField(default=False, help_text='Required for TKR — implant barcode/invoice'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='has_lft_report',
            field=models.BooleanField(default=False, help_text='Liver Function Test — required for Cholecystectomy'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='has_post_treatment_report',
            field=models.BooleanField(default=False, help_text='Post-op X-ray / Post-treatment Hb / Intra-op photo'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='has_postop_photo',
            field=models.BooleanField(default=False, help_text='Post-op clinical photograph — required for TKR'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='has_pre_anesthesia_report',
            field=models.BooleanField(default=False, help_text='Pre-anesthesia check-up — required for Cholecystectomy'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='has_preop_xray',
            field=models.BooleanField(default=False, help_text='Required for Revision TKR only'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='has_previous_cholecystectomy',
            field=models.BooleanField(default=False, help_text='FRAUD FLAG: Has patient had cholecystectomy before?'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='has_treatment_records',
            field=models.BooleanField(default=False, help_text='Antibiotic records / Blood transfusion / Iron injection'),
        ),
        migrations.CreateModel(
            name='ClaimPageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=200)),
                ('s3_link', models.CharField(blank=True, default='', max_length=1000)),
                ('procedure_code', models.CharField(max_length=10)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('document_type', models.CharField(blank=True, default='', help_text='Gemini-classified doc type for rank assignment', max_length=50)),
                ('clinical_notes', models.BooleanField(default=False)),
                ('discharge_summary', models.BooleanField(default=False)),
                ('extra_document', models.BooleanField(default=False)),
                ('document_rank', models.PositiveIntegerField(default=99)),
                ('cbc_hb_report', models.BooleanField(default=False)),
                ('indoor_case', models.BooleanField(default=False)),
                ('treatment_details', models.BooleanField(default=False)),
                ('post_hb_report', models.BooleanField(default=False)),
                ('severe_anemia', models.BooleanField(default=False, help_text='Hb < 7 g/dL — STG Section 3.2')),
                ('common_signs', models.BooleanField(default=False, help_text='Pallor, fatigue, weakness — STG Sec 1.2')),
                ('significant_signs', models.BooleanField(default=False, help_text='Tachycardia, breathlessness — STG Sec 1.2')),
                ('life_threatening_signs', models.BooleanField(default=False, help_text='Cardiac failure, shock, severe hypoxia — STG Sec 1.2')),
                ('usg_report', models.BooleanField(default=False)),
                ('lft_report', models.BooleanField(default=False)),
                ('operative_notes', models.BooleanField(default=False)),
                ('pre_anesthesia', models.BooleanField(default=False)),
                ('photo_evidence', models.BooleanField(default=False, help_text='Intra-op + gross specimen photos')),
                ('histopathology', models.BooleanField(default=False)),
                ('clinical_condition', models.BooleanField(default=False, help_text='Any of 5 clinical conditions present — STG Sec 1.2')),
                ('usg_calculi', models.BooleanField(default=False, help_text='USG confirms calculi — STG Sec 3.2')),
                ('pain_present', models.BooleanField(default=False, help_text='Pain in right hypochondrium / epigastrium')),
                ('previous_surgery', models.BooleanField(default=False, help_text='Prior cholecystectomy — fraud flag')),
                ('investigation_pre', models.BooleanField(default=False)),
                ('pre_date', models.CharField(blank=True, help_text='Date on pre-investigation report (DD/MM/YY)', max_length=20, null=True)),
                ('vitals_treatment', models.BooleanField(default=False, help_text='Vitals + treatment chart')),
                ('investigation_post', models.BooleanField(default=False)),
                ('post_date', models.CharField(blank=True, help_text='Date on post-investigation report (DD/MM/YY)', max_length=20, null=True)),
                ('poor_quality', models.BooleanField(default=False, help_text='Document/image quality is poor or unreadable')),
                ('fever', models.BooleanField(default=False, help_text='Fever criterion met — STG Sec 3.2.1')),
                ('symptoms', models.BooleanField(default=False, help_text='Any of 3 symptoms present — STG Sec 1.2')),
                ('xray_ct_knee', models.BooleanField(default=False)),
                ('implant_invoice', models.BooleanField(default=False)),
                ('post_op_photo', models.BooleanField(default=False)),
                ('post_op_xray', models.BooleanField(default=False)),
                ('doa', models.CharField(blank=True, help_text='Date of Admission from discharge summary (DD-MM-YYYY)', max_length=20, null=True)),
                ('dod', models.CharField(blank=True, help_text='Date of Discharge from discharge summary (DD-MM-YYYY)', max_length=20, null=True)),
                ('arthritis_type', models.BooleanField(default=False, help_text='Arthritis type classification — STG Sec 1.2')),
                ('post_op_implant_present', models.BooleanField(default=False, help_text='Post-op X-ray shows implant — STG Sec 3.2.2')),
                ('age_valid', models.BooleanField(default=False, help_text='Age >= 55 for primary OA — STG Sec 3.2.3')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_json', models.JSONField(blank=True, help_text='Raw Gemini extraction response for this page', null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_results', to='claims.claim')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
    ]
